name: recoverbull
description: "A new Flutter package project."
version: 1.0.0
homepage: "https://github.com/SatoshiPortal/recoverbull-client-dart"
publish_to: "none"
environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  http: ^1.3.0
  hex: ^0.2.0
  pointycastle: ^3.9.1
  tor:
    git:
      url: https://github.com/Foundation-Devices/tor
      ref: 440a2d2
  socks5_proxy: ^2.1.0
  http_parser: ^4.1.2

dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  dotenv: ^4.2.0
  flutter_test:
    sdk: flutter
