name: recoverbull
description: "A new Flutter package project."
version: 1.0.0
homepage: "https://github.com/SatoshiPortal/recoverbull-client-dart"
publish_to: "none"
environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.7.0
  hex: ^0.2.0
  bip32: ^2.0.0
  bip85: ^1.0.3
  bip39_mnemonic: ^3.0.7
  pointycastle: ^3.9.1

dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  test: ^1.25.14
  dotenv: ^4.2.0
