name: recoverbull_dart
description: "A new Flutter package project."
version: 0.0.1
homepage: "https://github.com/StaxoLotl/recoverbull-dart.git"
publish_to: "none"
environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  cryptography: ^2.7.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  freezed: ^2.4.5
  json_annotation: ^4.9.0
  pointycastle: ^3.9.1
  hex: ^0.2.0
  bip85:
    git:
      url: https://github.com/ethicnology/rust-bip85.git
      path: bindings/dart-bip85
      ref: master
  bip39_mnemonic: ^3.0.7
  dio: ^5.7.0
  bip32: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.9.2
