name: recoverbull
description: "recoverbull is a project designed to facilitate secure backup and recovery of data using encryption and key management techniques. It supports creating encrypted backups, restoring data from backups, and managing keys with a remote server."
version: 1.0.0
homepage: "https://github.com/SatoshiPortal/recoverbull-client-dart"
publish_to: "none"
environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  hex: ^0.2.0
  pointycastle: ^3.9.1

dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  dotenv: ^4.2.0
  flutter_test:
    sdk: flutter
