name: recoverbull
description: "A new Flutter package project."
version: 1.0.0
homepage: "https://github.com/SatoshiPortal/recoverbull-client-dart"
publish_to: "none"
environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  http: ^1.3.0
  hex: ^0.2.0
  bip32: ^2.0.0
  bip39_mnemonic: ^3.0.7
  pointycastle: ^3.9.1
  nostr:
    git:
      url: https://github.com/ethicnology/dart-nostr
      ref: develop
  tor:
    git:
      url: https://github.com/Foundation-Devices/tor
      ref: main
  socks5_proxy: ^2.0.0
  http_parser: ^4.1.2

dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  test: ^1.25.14
  dotenv: ^4.2.0
