// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

(String, String) generateNostrKeys() =>
    RustLib.instance.api.crateApiNostrGenerateNostrKeys();

(String, String) recoverNostrKeys({required String secret}) =>
    RustLib.instance.api.crateApiNostrRecoverNostrKeys(secret: secret);

String nip44Encrypt(
        {required String secretKey,
        required String publicKey,
        required String plaintext}) =>
    RustLib.instance.api.crateApiNostrNip44Encrypt(
        secretKey: secretKey, publicKey: publicKey, plaintext: plaintext);

String nip44Decrypt(
        {required String secretKey,
        required String publicKey,
        required String ciphertext}) =>
    RustLib.instance.api.crateApiNostrNip44Decrypt(
        secretKey: secretKey, publicKey: publicKey, ciphertext: ciphertext);
